In [ ]:
#name = ('AAAA','BBBB','DDDD','FFFF')   --> Datatype  np.str_
#age  = (23,24,15,16)                   -->           np.int8
#marks = (89.28,87.23,89.,24.25)         -->           np.float16

In [1]:
import numpy as np

In [20]:
#create datatype for student data structure
li=[('name',np.str_,20),
    ('age',np.int8),
   ('marks',np.float16)]

dt_student=np.dtype(li)

#Create Array
data= [('AAAA',24,89.23),
       ('BBBB',22,85.23),
       ('CCCC',24,81.23),
       ('DDDD',24,86.23)
       ]

ar=np.array(data,dt_student)
print(ar)

[('AAAA', 24, 89.25) ('BBBB', 22, 85.25) ('CCCC', 24, 81.25)
 ('DDDD', 24, 86.25)]


In [21]:
print(np.dtype)

<class 'numpy.dtype'>


In [24]:
print(ar[0]['name'])

AAAA


In [25]:
print(ar['name'])

['AAAA' 'BBBB' 'CCCC' 'DDDD']


In [26]:
print(ar['age'])

[24 22 24 24]


In [31]:
# Python Programming illustrating
# numpy.eye method

import numpy as np

# 2x2 matrix with 1's on main diagonal
b = np.eye(2,)
print("Matrix b : \n", b)



Matrix b : 
 [[1. 0.]
 [0. 1.]]


In [28]:
# matrix with R=4 C=5 and 1 on diagonal
# below main diagonal
a = np.eye(4, 5, k = -1)
print("\nMatrix a : \n", a)



Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [29]:
# matrix with R=4 C=5 and 1 on diagonal
# below main diagonal
a = np.eye(4, 5, k = 1)
print("\nMatrix a : \n", a)



Matrix a : 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
