In [4]:
import numpy as np

In [5]:
li=[[10,20,30],
    [11,22,33]]
print(type(li))
ar=np.asarray(li)
print(ar)
print(type(ar))

<class 'list'>
[[10 20 30]
 [11 22 33]]
<class 'numpy.ndarray'>


In [6]:
ar=np.arange(1,11,1,dtype=int)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
ar=np.arange(1,11,1,dtype=float)
print(ar)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
ar=np.arange(10,0,-1,dtype='i8')
print(ar)
print(ar.dtype)

[10  9  8  7  6  5  4  3  2  1]
int64


In [9]:
ar=np.linspace(1,10,5)
print(ar)

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
ar=np.linspace(1,10,5,dtype=int)
print(ar)

[ 1  3  5  7 10]


In [11]:
ar=np.linspace(10,20)
print(ar)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [12]:
ar=np.linspace(10,20,dtype=int)
print(ar)

[10 10 10 10 10 11 11 11 11 11 12 12 12 12 12 13 13 13 13 13 14 14 14 14
 14 15 15 15 15 15 16 16 16 16 16 17 17 17 17 17 18 18 18 18 18 19 19 19
 19 20]


In [13]:
ar=np.linspace(10,20,5)
print(ar)

[10.  12.5 15.  17.5 20. ]


In [14]:
ar=np.linspace(10,20,5,endpoint=False)
print(ar)

[10. 12. 14. 16. 18.]


In [15]:
ar=np.linspace(10,20,5,endpoint=False,retstep=True)
print(ar)
print(ar[0])
print(ar[1])


(array([10., 12., 14., 16., 18.]), np.float64(2.0))
[10. 12. 14. 16. 18.]
2.0


In [16]:
ar,step=np.linspace(10,20,5,endpoint=False,retstep=True)
print(ar)
print("interval size: ",step)


[10. 12. 14. 16. 18.]
interval size:  2.0


In [17]:
a,b,c=(10,20,30)
print(a)
print(b)
print(c)

10
20
30


In [18]:
s= b'hello world'
print(s)

b'hello world'


In [19]:
print(type(s))

<class 'bytes'>


In [20]:
bb=[10,20,30]      #range(0,256)
print(bytes(bb)) 
print(bb)

b'\n\x14\x1e'
[10, 20, 30]


In [21]:
s = b'hello world'            #A --> 65  B --> 66..  ASCCI 0 to 256 
print(type(s))                
a = np.frombuffer(s, dtype = "S1")  
print(a)  
print(type(a))  



<class 'bytes'>
[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
<class 'numpy.ndarray'>


In [22]:
print(a[0])
print(a[1])

b'h'
b'e'


## array cration  fromiter function

In [27]:
li=[10,20,30,40,50]

ii=iter(li)
print(next(ii))
print(next(ii))
print(next(ii))

10
20
30


In [28]:
ar=np.fromiter(ii,dtype=float)
print(ar)

[40. 50.]
