In [1]:
import numpy.random as rd

In [16]:
#random value 0 to 1
ar=rd.rand(100)
print(ar)

[0.7309039  0.86592034 0.49842358 0.24263314 0.65628242 0.30102349
 0.78045539 0.97099076 0.1251226  0.09209056 0.14037175 0.41034263
 0.78705731 0.42792443 0.20945744 0.38429509 0.87266741 0.71755459
 0.68584057 0.42829222 0.30504634 0.96340732 0.40696113 0.58337484
 0.21517623 0.76869116 0.70785041 0.59676113 0.99054602 0.91043323
 0.18393765 0.83028593 0.89569931 0.94852767 0.52537886 0.09133565
 0.85816691 0.5268333  0.46404836 0.06980713 0.52164855 0.2766789
 0.88780545 0.09959308 0.55633943 0.57706451 0.21357688 0.48260806
 0.25236426 0.1756014  0.82293962 0.7794753  0.05671446 0.12702061
 0.16739797 0.6921916  0.44532259 0.39813756 0.89588185 0.36333764
 0.12038668 0.86475748 0.89709088 0.62209771 0.96096216 0.59843769
 0.14623051 0.2655936  0.450519   0.26761427 0.38350633 0.76809546
 0.94293385 0.37488934 0.03511388 0.60341541 0.55140536 0.18090246
 0.91586351 0.52553606 0.01016379 0.70286958 0.79423705 0.57419236
 0.30653404 0.94826999 0.1821334  0.33783085 0.74576403 0.10967

In [6]:
ar=rd.rand(10)
print(ar)

[0.00103254 0.94947191 0.78177825 0.57805863 0.51749809 0.08696084
 0.50542572 0.2047624  0.45087858 0.54940699]


In [7]:
ar_2d=rd.rand(2,3)
print(ar_2d)

[[0.10336769 0.63484007 0.59165604]
 [0.4013763  0.77274339 0.19703325]]


In [9]:
ar_3d =rd.rand(4,2,3)
print(ar_3d)

[[[0.64035721 0.87610786 0.50498385]
  [0.2481883  0.62291517 0.68695808]]

 [[0.77623389 0.36939684 0.01002776]
  [0.52421493 0.34427789 0.54959793]]

 [[0.36143624 0.2829391  0.58440013]
  [0.96121901 0.25143127 0.89582185]]

 [[0.23915324 0.75241724 0.8331987 ]
  [0.63597652 0.77404738 0.73815174]]]


In [11]:
# randn()

ar=rd.randn(100)
print(ar)

[-5.38222624e-01 -4.32962452e-01 -2.02012344e-01 -2.67412239e-01
  1.19838216e+00 -3.91984904e-01 -1.57246717e+00 -1.24581375e+00
  1.39943583e-03  1.77857645e-01  5.73543493e-01  9.53021071e-01
 -7.51266234e-01  1.40970090e+00  1.56453112e+00 -2.02129742e+00
  1.54795766e+00  9.10327976e-01 -1.18761117e+00 -1.42960360e+00
  1.32366295e+00 -1.02569438e-01 -4.83743487e-01 -9.44344823e-01
 -1.59301414e+00  1.37457174e+00 -1.07665316e+00  1.21775590e-01
 -1.10365199e+00  3.97411839e-01 -8.12609818e-01  6.31415539e-01
  4.93512017e-01 -6.00297789e-01  7.83968298e-01 -4.96170436e-01
  1.06054041e+00 -2.03189109e-01 -1.87607100e+00  1.98685050e-01
  4.59232312e-01 -1.22048251e+00  3.27693235e-01  9.89277839e-01
  7.13952341e-01  1.27731285e+00  1.16557372e+00 -6.25445162e-01
  7.16141821e-01  7.75616152e-01  6.13774088e-01 -4.38940957e-02
  6.24383744e-02 -1.24218667e+00  2.40499696e-01  3.56617411e-01
 -1.75511379e-03  1.59979735e+00 -7.25603989e-01  2.12414349e-01
  1.83066095e+00 -4.52839

In [14]:
ar=rd.randn(100)
print(ar)

[-1.39896043e+00 -6.10505105e-01  8.35660351e-01  2.75464607e-01
  2.03664255e-02  5.76929571e-01  1.33253967e+00 -1.80413425e+00
 -2.85593507e-01 -1.01830598e+00 -3.19452736e-01  1.69254806e-01
  1.01849328e+00  4.50115007e-02  1.19957646e+00 -1.42426562e+00
  4.49196481e-01  1.21514941e+00  1.40253242e+00 -6.95653731e-01
  5.27540897e-01 -5.54300663e-01 -2.20559935e+00 -7.37160089e-01
  1.14449574e+00 -3.80422668e-01  5.26773113e-01  2.14804784e-01
  1.32436515e+00  9.42579721e-01  9.65461864e-01  2.36435534e+00
  4.67669541e-01 -1.10280248e+00 -1.11486214e+00 -1.09125593e+00
  1.35873508e+00  4.80638290e-01  1.08633340e+00 -5.95657265e-01
 -6.52976493e-01  1.56985029e+00 -2.34585262e-01 -5.69092462e-01
 -2.06305939e-01 -1.89753084e+00  4.99508000e-01 -1.68777155e+00
  2.52002900e+00  6.02074264e-01 -2.43318638e-01  3.36415677e-01
 -7.41453088e-01  2.99491376e-01  3.01503790e-01  6.34832065e-01
  5.46564629e-01 -6.03059211e-01  3.10067712e-01  1.63144248e-01
  3.02559696e-01 -9.63779

In [18]:
#ranf()

ar=rd.ranf(5)
print(ar)

[0.67605955 0.37939501 0.38414565 0.98251279 0.45016129]


In [19]:
#randint()

ar=rd.randint(1,100,size=5)
print(ar)

[31 69 96 33 19]


In [21]:
#2d array
ar=rd.randint(1,1000,size=(2,3))
print(ar)

[[248 133 533]
 [678 697 839]]


In [23]:
#3rd array using randint()
ar=rd.randint(1,100,size=(4,2,3))
print(ar)


[[[50 17 38]
  [35 79  4]]

 [[10  5 98]
  [94 46 52]]

 [[55 66 54]
  [ 2 84  5]]

 [[31  3 76]
  [32 44  2]]]


In [35]:
#as a argument dimension
ar= rd.rand(1,2,3,4)
print(ar)

[[[[0.18887811 0.43899092 0.00788543 0.8673845 ]
   [0.61793408 0.58583611 0.15339842 0.56490632]
   [0.71441216 0.35125234 0.82366523 0.91519922]]

  [[0.74190102 0.87507665 0.8599418  0.67298592]
   [0.14104133 0.74237554 0.80337754 0.68265871]
   [0.52425063 0.76828102 0.56401976 0.39936685]]]]


In [37]:
ar=rd.ranf(size=(4,2))
print(ar)

[[0.9030494  0.86348114]
 [0.07245638 0.91035319]
 [0.64365087 0.10449997]
 [0.52638078 0.48292848]]
