#### Boardcastiong

In [6]:
import numpy as np

In [21]:
ar1=np.array([[1,2,3,4,5],
             [11,22,33,44,55]])
print(ar1)
print('-------------------')
print(ar1.shape)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
-------------------
(2, 5)


In [22]:
print(ar1+10)

[[11 12 13 14 15]
 [21 32 43 54 65]]


In [23]:
ar2=np.array([10,20])   #-->error      #shape (5,)
print(ar1+ar2)             #[10 10 10 10 10]
print(ar2.shape)

ValueError: operands could not be broadcast together with shapes (2,5) (2,) 

In [24]:
ar3=np.array([10,20,30,40,50])
print(ar3)
print(ar3.shape)

[10 20 30 40 50]
(5,)


In [25]:
print(ar1+ar3)

[[ 11  22  33  44  55]
 [ 21  42  63  84 105]]


In [32]:
a1=np.array([1,2,3])
print(a1)
print('---------------')
print(a1.shape)

[1 2 3]
---------------
(3,)


In [31]:
a2=np.array([
             [10],
             [20],
             [30]
            ])
print(a2)
print('-----------')
print(a2.shape)

[[10]
 [20]
 [30]]
-----------
(3, 1)


In [34]:
#print(a1+a2)
x=a1+a2
print(x)
print(x.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


In [ ]:
#BoardCastable
# n-->row
# m--> col

#(n,m) --> (n,m)
# (n,m) --> (n,1)
# (n,m) --> (m,)

In [38]:
#(n,m) --> (n,m)

a1=np.array([[1,2],    #shape --> (2,2)
             [3,4]])

a2=np.array([[10,20],   #shape --> (2,2)
            [30,40]])
print(a1+a2)

[[11 22]
 [33 44]]


In [39]:
# (n,m) --> (n,1)

a1=np.array([[1,2],    #shape --> (2,2)
             [3,4]])

a2=np.array([[10],    #shape -->(2,1)
             [20]])

print(a1+a2)

[[11 12]
 [23 24]]


In [40]:
# (n,m) --> (m,)

a1=np.array([[1,2],    #shape --> (2,2)
             [3,4]])

a2=np.array([10,20])  #shape(2,)
print(a1+a2)

[[11 22]
 [13 24]]


In [42]:
import numpy as np 

v = np.array([1, 2, 3]) 
w = np.array([4, 5])	 

print(v)
print(w)

print(v.shape)


[1 2 3]
[4 5]
(3,)


In [43]:
re=np.reshape(v, (3, 1))
print(re)

[[1]
 [2]
 [3]]


In [44]:
# Outer product of vectors v and w 
print(np.reshape(v, (3, 1)) * w) 



[[ 4  5]
 [ 8 10]
 [12 15]]


In [45]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]]) 

# # Broadcasting vector v to matrix x 
print(x + v) 


[[2 4 6]
 [5 7 9]]
