In [1]:
import numpy as np

In [2]:
# Making a view and changing the original array
# # creating array 

ar = np.array([2, 4, 6, 8, 10]) 
# creating view 
v = ar.view() 

print(ar)
print(v)

[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [4]:
# both arr and v have different id 
print("id of arr", id(ar)) 
print("id of v", id(v)) 


id of arr 2426433123984
id of v 2426638517904


In [5]:
# changing original array 
# will effect view 
ar[0] = 12

# printing array and view 
print("original array- ", ar) 
print("view- ", v)


original array-  [12  4  6  8 10]
view-  [12  4  6  8 10]


In [6]:
v[2]=56
print("original array- ", ar) 
print("view- ", v)


original array-  [12  4 56  8 10]
view-  [12  4 56  8 10]


#### copy array

In [9]:
#original array
ar=np.array([11,22,33,44])
print(ar)

#copy array
cp=ar.copy()
print(cp)

[11 22 33 44]
[11 22 33 44]


In [11]:
print('Original array id-> ',id(ar))
print('Copy array id -> ',id(cp))

Original array id->  2426639560176
Copy array id ->  2426639558448


In [14]:
ar[0]=99
print('Original--> ',ar)
print('Copy Array--> ',cp)

Original-->  [99 22 33 44]
Copy Array-->  [11 22 33 44]


In [15]:
cp[2]=88
print('Original--> ',ar)
print('Copy Array--> ',cp)

Original-->  [99 22 33 44]
Copy Array-->  [11 22 88 44]


#### Swiping Array

In [16]:
#Swapping the column of an array. 

# creating array with shape(4,3)
ar = np.arange(12)
print("Original array:")
print(ar)



Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
ar = np.arange(12).reshape(4,3)
print("Original array:")
print(ar)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
#Swiping The array 
print(ar[:,[0,2]])

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [23]:
ar[:,[0,2]] = ar[:,[2,0]]
print('After swiping ')
print(ar)

After swiping 
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [24]:
#swiping in row
ar=np.array([[11,22],
             [23,24],
             [10,20]])
print(ar)

[[11 22]
 [23 24]
 [10 20]]


In [25]:
print(ar[[0,2],])

[[11 22]
 [10 20]]


In [26]:
ar[[0,2],] =ar[[2,0],]
print('Array after swiping')
print(ar)

Array after swiping
[[10 20]
 [23 24]
 [11 22]]


In [29]:
import numpy as np

arr = np.arange(5*5).reshape(5, 5)
print(arr)
print(arr.shape)        #2d array



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [32]:
# promoting 2D array to a 3D array
# arr[None, ..., None, None]
arr_3D = arr[np.newaxis]

print(arr_3D.shape)


(1, 5, 5)


In [33]:
# promoting 2D array to a 4D array
# arr[None, ..., None, None]
arr_4D = arr[np.newaxis,np.newaxis]

print(arr_4D.shape)


(1, 1, 5, 5)


In [34]:
# promoting 2D array to a 5D array
# arr[None, ..., None, None]
arr_5D = arr[np.newaxis,np.newaxis,np.newaxis]

print(arr_5D.shape)


(1, 1, 1, 5, 5)
