In [1]:
import numpy as np

In [17]:
ar=np.array([1,2,3,4,5,6,7])
print(ar)

[1 2 3 4 5 6 7]


In [18]:
#unequal spling
x=np.array_split(ar,3)
print(x)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [9]:
print(x[0])
print(x[1])
print(x[2])

[1 2]
[3 4]
[5 6]


In [20]:
#equal spliting
ar=np.array([10,20,30,40,50,60,40,50])
print(ar)

[10 20 30 40 50 60 40 50]


In [21]:
x=np.split(ar,4)
print(x)

[array([10, 20]), array([30, 40]), array([50, 60]), array([40, 50])]


In [23]:
# Creating a 2D array
array = np.array([[3, 2, 1], 
                  [8, 9, 7], 
                  [4, 6, 5]])

print("2D Array:")
print(array)


2D Array:
[[3 2 1]
 [8 9 7]
 [4 6 5]]


In [26]:
# Splitting the array into 3 equal parts along the second axis (axis=1)

result = np.split(array,3,axis=1)

print("\nResult after numpy.split() along axis=1:")
print(result)



Result after numpy.split() along axis=1:
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


In [27]:
print(result[0])

[[3]
 [8]
 [4]]


In [28]:
print(result[1])

[[2]
 [9]
 [6]]


In [29]:
print(result[2])

[[1]
 [7]
 [5]]


In [30]:
result = np.split(array,3,axis=0)

print("\nResult after numpy.split() along axis=0:")
print(result)



Result after numpy.split() along axis=0:
[array([[3, 2, 1]]), array([[8, 9, 7]]), array([[4, 6, 5]])]
