In [1]:
import numpy as np

In [17]:
arr = np.arange(2*2).reshape(2,2)
print(arr.shape)
print(arr)


(2, 2)
[[0 1]
 [2 3]]


In [24]:
newaxes = (1,0)
arr_5D = np.expand_dims(arr, axis=newaxes)
print(arr_5D.shape)
print(arr_5D)


(1, 1, 2, 2)
[[[[0 1]
   [2 3]]]]


#### numpy.hstack

In [28]:
a1=np.array([1,2,3,4])
print(a1)

a2=np.array([10,20,30])
print(a2)

[1 2 3 4]
[10 20 30]


In [30]:
new_ar=np.hstack((a1,a2))
print(new_ar)

[ 1  2  3  4 10 20 30]


In [32]:
#2D array

a1=np.array([[10,20],
             [11,22]])
a2=np.array([[1,2],
             [3,4]])

new_ar=np.hstack((a1,a2))
print(new_ar)
print(new_ar.shape)

[[10 20  1  2]
 [11 22  3  4]]
(2, 4)


#### vstack

In [38]:
a1=np.array([1,2,3,4])
print(a1)

a2=np.array([10,20,30,50])
print(a2)

a3=np.array([11,22,33,44])
print(a3)

[1 2 3 4]
[10 20 30 50]
[11 22 33 44]


In [40]:
v_arr=np.vstack((a1,a2,a3))
print(v_arr)
print(v_arr.shape)

[[ 1  2  3  4]
 [10 20 30 50]
 [11 22 33 44]]
(3, 4)


In [41]:
#2d array  vertically merge

a1=np.array([[1,2],
             [3,4]])
a2=np.array([[-1,-2],
             [-3,-4]])

a3=np.array([[3,5],
             [7,9]])

new_ar=np.vstack((a1,a2,a3))
print(new_ar)



[[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]
 [ 3  5]
 [ 7  9]]


In [42]:
#Method 1: Using numpy.concatenate()
ar_1 = np.array([1, 2]) 
ar_2 = np.array([3, 4]) 

ar_new = np.concatenate((ar_1, ar_2)) 
print(ar_new) 


[1 2 3 4]


In [43]:
array_1 = np.array([[1, 2], 
                    [3, 4]]) 
array_2 = np.array([[5, 6], 
                    [7, 8]]) 

array_new = np.concatenate((array_1,array_2), axis=1) 
print(array_new) 


[[1 2 5 6]
 [3 4 7 8]]


In [44]:
array_new = np.concatenate((array_1,array_2), axis=0) 
print(array_new) 


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
#Method 2: Using numpy.stack()
import numpy as np 

array_1 = np.array([1, 2, 3, 4]) 

array_2 = np.array([5, 6, 7, 8]) 

array_new = np.stack((array_1, array_2),axis=1) 
print(array_new) 


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [46]:
array_new = np.stack((array_1, array_2),axis=1) 
print(array_new) 


[[1 2 3 4]
 [5 6 7 8]]


In [50]:
#numpy.dstack() -> combined array index by index and store like a stack
print(np.dstack((array_1,array_2))) 


[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [51]:
#Method 3: numpy.block()


block_1 = np.array([[1, 1], [1, 1]])   #--2x2

block_2 = np.array([[2, 2, 2], [2, 2, 2]])   #-->2x3

block_3 = np.array([[3, 3],[3, 3],[3, 3]])  #   3x2

block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])  #3x3 

block_new = np.block([[block_1,block_2],
                      [block_3,block_4]])
print(block_new)


[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]
