In [1]:
import numpy as np

In [11]:
a1=np.array([[1,2,3],
            [4,5,6]])
a2=np.array([[1,2,3],
            [4,5,6],
            ])

#print(a1==a2)
comperision_array = a1==a2
print(comperision_array)

[[ True  True  True]
 [ True  True  True]]


In [9]:
equal_arrays = comperision_array.all()
print(equal_arrays)


True


In [16]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[1,1],[3,3]])

x=a1==a2
print(x)
print('----------')
print(x.all())

[[ True  True]
 [False False]]
----------
False


In [17]:
print(x.all(axis=1))  #col 1 

[ True False]


In [18]:
print(x.all(axis=0))  #col 2

[False False]


In [21]:
print(x[0].all())

True


In [20]:
print(x[1].all())

False


In [24]:
a1=np.array([[1,1],[10,2]])
a2=np.array([[1,1],[3,3]])

In [28]:
print(a1>a2)
print(np.greater(a1,a2))



[[False False]
 [ True False]]
[[False False]
 [ True False]]


In [31]:
print(a1<a2)
print(np.less(a1,a2))      

[[False False]
 [False  True]]
[[False False]
 [False  True]]


In [ ]:
#a1 >= a2    or    np.greater_equal()
#a1 <=a2     or    np.less_equal()


In [36]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

x=np.array_equal(arr1, arr2)
print(x)
# # Comparing the arrays
if x:
 	print("Equal")
else:
 	print("Not Equal")


True
Equal


#### Find union of Two numpy array

In [37]:
arr1 = np.array([10, 20, 30, 40]) 
print("array1 ", arr1) 

arr2 = np.array([20, 40, 60, 80]) 
print("array2 ", arr2) 


array1  [10 20 30 40]
array2  [20 40 60 80]


In [38]:

# print union of the two arrays 
print("Union of two arrays :", np.union1d(arr1, arr2)) 


Union of two arrays : [10 20 30 40 60 80]


In [41]:
arr1 = np.array([10, 20, 30, 40]) 
print("array1 ", arr1) 

arr2 = np.array([20, 40, 60, 80]) 
print("array2 ", arr2) 

arr3 = np.array([34, 20, 30, 18]) 
print("array3 ", arr3) 

arr4 = np.array([17, 40, 60, 72]) 
print("array4 ", arr4) 


array1  [10 20 30 40]
array2  [20 40 60 80]
array3  [34 20 30 18]
array4  [17 40 60 72]


In [52]:
# print union of the multipal arrays 
print("Union of arrays :", np.union1d(arr1,(arr2,arr3,arr4))) 


Union of arrays : [10 17 18 20 30 34 40 60 72 80]


In [51]:
from functools import reduce
x=reduce(np.union1d,(arr1,arr2,arr3,arr4))
print(x)

[10 17 18 20 30 34 40 60 72 80]


#### Find Unque rows and cols

In [54]:
# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
        		  [13, 11, 12, 11],
        		  [16, 11, 12, 11],
            	  [11, 11, 12, 11]])
uniqueRows = np.unique(arr2D, axis=0)
# print the output result
print('Unique Rows:',uniqueRows, sep = '\n')


Unique Rows:
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]


In [59]:
uniqueRows = np.unique(arr2D, axis=1)
# print the output result
print('Unique Rows:\n',uniqueRows)


Unique Rows:
 [[11 11 12]
 [11 13 12]
 [11 16 12]
 [11 11 12]]


#### trim_Zero

In [63]:
ar= np.array([0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0]) 
print(ar)


[ 0  0  0  0  1  5  7  0  6  2  9  0 10  0  0]


In [64]:
# without trim parameter 
# returns an array without leading and trailing zeros 
res = np.trim_zeros(ar) 
print(res) 


[ 1  5  7  0  6  2  9  0 10]
