In [1]:
import numpy as np

In [2]:
a1=np.array([[1,2],
           [3,4]])

a2=np.array([[5,6],
             [7,8]])

#element wise multipication
print(np.multiply(a1,a2))

[[ 5 12]
 [21 32]]


In [3]:
#matrix multipication
print(np.dot(a1,a2))

[[19 22]
 [43 50]]


#### Matrix Manuplation

In [5]:
print(np.sqrt(a2))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [10]:
print(a2)

[[5 6]
 [7 8]]


In [6]:
print(np.sum(a2))

26


In [7]:
print(np.sum(a2,axis=0))  

[12 14]


In [8]:
print(np.sum(a2,axis=1))

[11 15]


In [11]:
ar=np.array([[10,20],
             [30,40]])
print(ar)

[[10 20]
 [30 40]]


In [12]:
print(ar.T)

[[10 30]
 [20 40]]


In [13]:
ar=np.array([[11,22,33],
             [10,20,30]])

rl=len(ar)
cl=len(ar[0])
print('length of row: ',rl)
print('length of col: ',cl)

length of row:  2
length of col:  3


In [16]:
rl=len(ar)
cl=len(ar[0])

for i in range(0,rl):
    print(ar[i])

[11 22 33]
[10 20 30]


In [18]:
for row in range(0,rl):
    for col in range(0,cl):
        print(ar[row][col])
    print()    
    

11
22
33

10
20
30



In [20]:
A = [[1,2],
     [4,5]] 
B = [[10,20],
     [30,40]]

C=[[0,0],
   [0,0]]
for row in range(0,2):
    for col in range(0,2):
        C[row][col]=A[row][col] + B[row][col]

print(C)    

[[11, 22], [34, 45]]


In [21]:
rows = len(A) 
cols = len(A[0]) 

# Element wise addition 
C = [[0 for i in range(cols)] for j in range(rows)] 
print(C)


[[0, 0], [0, 0]]


In [23]:
for i in range(rows): 
    for j in range(cols): 
        C[i][j] = A[i][j] / B[i][j] 
print("Addition of matrices: \n", C) 


Addition of matrices: 
 [[0.1, 0.1], [0.13333333333333333, 0.125]]


#### Matlib

In [26]:
from numpy import matlib as mt

x=mt.empty((2,3),dtype=int,order='C')
print(x)

[[   4294967296 2875398470112             0]
 [            0             0             0]]


In [27]:
ones=mt.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
zeros=mt.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [32]:
ii=mt.identity(3)
print(ii)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
ii=mt.eye(3,k=-1)
print(ii)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
