#### np.insert()

In [2]:
import numpy as np

In [3]:
ar=np.array([10,20,30,40])
print(ar)

[10 20 30 40]


In [5]:
# index 2 insert [11,22]
new_ar=np.insert(ar,2,[11,22])
print(ar)
print(new_ar)

[10 20 30 40]
[10 20 11 22 30 40]


In [6]:
ar=np.array([[1,2],
             [3,4]])
print(ar)

[[1 2]
 [3 4]]


In [11]:
#insert elements along the rows
new_ar=np.insert(ar,1,[10,20],axis=1)
print(new_ar)

[[ 1 10  2]
 [ 3 20  4]]


In [13]:
#insert elemnts along the rows
new_ar2=np.insert(ar,0,[11,22],axis=0)
print(new_ar2)

[[11 22]
 [ 1  2]
 [ 3  4]]


In [16]:
#. Inserting using a boolean mask
arr = np.array([5, 10, 15, 20, 25])

# Insert 0 before all even numbers
mask = arr % 2 == 0        #even condition
new_arr = np.insert(arr,np.flatnonzero(mask),0)
print(new_arr)  


[ 5  0 10 15  0 20 25]


In [18]:
#1. Deleting a range of elements:
arr = np.array([10, 20, 30, 40, 50, 60])

# Delete elements from index 1 to 3 (exclusive)
new_arr = np.delete(arr, slice(1, 4))
print(new_arr)  # Output: [1 5 6]



[10 50 60]


In [19]:
#2. Deleting elements based on a condition:
arr = np.array([10, 5, 15, 20, 2, 25])

# Delete elements greater than 10
new_arr = np.delete(arr, np.where(arr > 10))
print(new_arr)  # Output: [5 2 25]


[10  5  2]


In [20]:
#3. Deleting along a specific axis (2D array):


arr = np.array([[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]])

# Delete the second row
new_arr = np.delete(arr, 1, axis=0)
print(new_arr)  


[[1 2 3]
 [7 8 9]]


In [21]:
# Delete the 3rd col
new_arr = np.delete(arr, 2, axis=1)
print(new_arr)  


[[1 2]
 [4 5]
 [7 8]]
