#### Statistics functions in numpy

In [ ]:
# np.mean()  # to Airhtemetic mean
# np.median() # to find median
# np.std()    # to find standart devioation
# np.var()    # to find variance
# np.min()
# np.max()
# np.percentile()   # give percentile value
# np.avrage()     # mean with optional weights
# np.argmax()     # index of max value
# np.argmin()     # index of min

In [15]:
import numpy as np
ar=np.array([10,20,40,30,40,50,])
print(np.mean(ar))


31.666666666666668


In [3]:
print(np.median(ar))

30.0


In [4]:
print(np.std(ar))

14.142135623730951


In [5]:
print(np.var(ar))

200.0


In [6]:
print(np.max(ar))

50


In [7]:
print(np.min(ar))

10


In [8]:
#index of max value
print(np.argmax(ar))

4


In [9]:
#index of min
print(np.argmin(ar))

0


In [12]:
print(np.percentile(ar,90))

46.0


In [16]:
print(np.quantile(ar,0.25))   #0 to 1     
                                   # 25%   0.25 1st quterlie
                                   # 50%   0.5  2nd quterlie
                                   # 75%   0.75  3rd  quterlie
                                   # 100%  1.0   4th quterlie

22.5


In [17]:
print(np.quantile(ar,0.50))   #0 to 1     
                                   # 25%   0.25 1st quterlie
                                   # 50%   0.5  2nd quterlie
                                   # 75%   0.75  3rd  quterlie
                                   # 100%  1.0   4th quterlie

35.0


In [18]:
ar=np.array([10,40,30,20,29])
print(ar)

[10 40 30 20 29]


In [20]:
print(np.sort(ar))

[10 20 29 30 40]


In [19]:
#index value with sorting
print(np.argsort(ar))

[0 3 4 2 1]


In [22]:
ar=np.array([10,np.nan,30,40,50])
print(np.isnan(ar))

[False  True False False False]
