In [1]:
import numpy as np

In [5]:
#1-d array
ar=np.array([10,20,30,40])
print(ar)
print(ar[0])
print(ar[1])
print(ar[-1])

[10 20 30 40]
10
20
40


In [6]:
print(ar[0:2])

[10 20]


In [13]:
#2-d Array
ar=np.array([[11,22,33],
             [10,20,30]])

print(ar)
print('----------')
print(ar[0])
print(ar[1])
print('------------')
print(ar[0][0])
print(ar[1][0])

[[11 22 33]
 [10 20 30]]
----------
[11 22 33]
[10 20 30]
------------
11
10


In [14]:
print(len(ar))

2


In [16]:
print(len(ar[0]))
print(len(ar[1]))

3
3


In [19]:
#i -->row  j--> col
for i in range(0,len(ar)):
    for j in range(0,len(ar[i])):
        print(ar[i][j],end=' ')
    print()

11 22 33 
10 20 30 


In [20]:
#Slicing
print(ar[0:1])

[[11 22 33]]


In [21]:
print(ar[0:2])

[[11 22 33]
 [10 20 30]]


In [23]:
print(ar[0:2,0:2])

[[11 22]
 [10 20]]


In [24]:
print(ar[0:2,0:1])

[[11]
 [10]]


In [27]:
ar=np.array([
             [11,22,33],
             [10,20,30],
             [21,22,33],
             [24,25,26]
            ])
#rows--> 4 col-->3

print(ar)


[[11 22 33]
 [10 20 30]
 [21 22 33]
 [24 25 26]]
[11 22 33]


In [29]:
print(ar[0])
print(ar[1])

[11 22 33]
[10 20 30]


In [30]:
print(ar[0:3])

[[11 22 33]
 [10 20 30]
 [21 22 33]]


In [31]:
print(ar[0:4])

[[11 22 33]
 [10 20 30]
 [21 22 33]
 [24 25 26]]


In [32]:
print(ar[0:4,0:1])

[[11]
 [10]
 [21]
 [24]]


In [34]:
print(ar[0:4,1:2])

[[22]
 [20]
 [22]
 [25]]


In [35]:
print(ar[0:4,0:2])

[[11 22]
 [10 20]
 [21 22]
 [24 25]]


In [37]:
print(ar[0:4,1:3])

[[22 33]
 [20 30]
 [22 33]
 [25 26]]


In [38]:
print(ar[3])

[24 25 26]


In [39]:
print(ar[3][1])

25
