In [1]:
import numpy as np

In [2]:
ar=np.array([
            [[10,20],[30,40]],
            [[33,44],[55,66]],
            [[21,22],[23,24]]
            ])
print(ar)

[[[10 20]
  [30 40]]

 [[33 44]
  [55 66]]

 [[21 22]
  [23 24]]]


In [6]:
print(ar[0])   #layer1

[[10 20]
 [30 40]]


In [4]:
print(ar[1])   #layer2

[[33 44]
 [55 66]]


In [5]:
print(ar[2]) #laryer3

[[21 22]
 [23 24]]


In [7]:
print(ar[0][0])

[10 20]


In [8]:
print(ar[0][0][0])

10


In [9]:
print(ar[0][0][1])

20


In [13]:
print(ar[0:2])

[[[10 20]
  [30 40]]

 [[33 44]
  [55 66]]]


In [14]:
print(ar[0:2,0:1])

[[[10 20]]

 [[33 44]]]


In [15]:
print(ar[0:2,0:1,0:1])

[[[10]]

 [[33]]]


In [17]:
l1=[11,22,33]
l2=[10,20,30]
l3=[21,22,23]

#2d array
ar=np.array([l1,
             l2,
             l3])   
print(ar)
print("Shape: ",ar.shape)

[[11 22 33]
 [10 20 30]
 [21 22 23]]
Shape:  (3, 3)


In [24]:
ar_3d=np.array([
            [[10,20],
             [30,40],
             [30,40]],
              
             [[33,44],
             [55,66],
             [30,40]],
            
            [[21,22],
             [23,24],
             [30,40]]
            
           ])
print(ar_3d.shape)    #shape 3 layer 2 rows 2 col

(3, 3, 2)


In [27]:
x=np.array([[10,20,30],
            [11,22,33]])
print(x)
print(x.shape)


[[10 20 30]
 [11 22 33]]
(2, 3)


In [29]:
#identify the type data 
a1=np.array([10,20,30])
print(a1)
print(a1.dtype)

[10 20 30]
int64


In [31]:
a2=np.array([10.23,19.24,23.24])
print(a2)
print(a2.dtype)

[10.23 19.24 23.24]
float64


In [37]:
a3=np.array(['Abc',10.23,30])
print(a3)
print(a3.dtype)


['Abc' '10.23' '30']
<U32
