In [65]:
import numpy as np


In [66]:
ar=np.array([[11,22,33],
             [10,20,30],
            [10,20,30]])
print(ar)
print(type(ar))

[[11 22 33]
 [10 20 30]
 [10 20 30]]
<class 'numpy.ndarray'>


In [67]:
print(ar.shape)

(3, 3)


In [68]:
print(ar.dtype)

int64


In [69]:
print(ar.ndim)   #dimesion 1d,2d,3d

2


In [70]:
print("Size of array: ",ar.size)

Size of array:  9


In [71]:
data=[[10,20],[11,22]]
ar=np.array(data,dtype='float')
print(ar)
print(ar.dtype)

[[10. 20.]
 [11. 22.]]
float64


In [72]:
#zero matrix / zero array
ar=np.zeros((3,4))
print(ar)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [73]:
#identity matrix/ ones arry
ar=np.ones((2,3),dtype='int')
print(ar)

[[1 1 1]
 [1 1 1]]


In [74]:
n=5
ar=np.full((3,4),n)
print(ar)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [75]:
n=5.3
ar=np.full((3,4),n,dtype='int')
print(ar)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [76]:
ar=np.array([[11,22,33,44],
             [10,20,30,40],
            [10,20,30,40],
            [10,20,30,40]])

print(ar)


[[11 22 33 44]
 [10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]


In [77]:
x=ar[:2,:1]
print(x)

[[11]
 [10]]


In [81]:
x=ar[[0,1,2,3]]
print(x)

[[11 22 33 44]
 [10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]


In [80]:
x=ar[[0,1,2,3],[3]]
print(x)

[44 40 40 40]


In [85]:
x=ar[[0,1,2,3],[3,2,1,0]]
print(x)

[44 30 20 10]


In [91]:
x=ar[::,3::-1]
print(x)

[[44 33 22 11]
 [40 30 20 10]
 [40 30 20 10]
 [40 30 20 10]]


In [92]:
x=(ar>=30)
print(x)

[[False False  True  True]
 [False False  True  True]
 [False False  True  True]
 [False False  True  True]]


In [93]:
x=(ar>=30)
print(ar[x])

[33 44 30 40 30 40 30 40]


In [95]:
x=np.where(ar>=20)
print(x)   #index values
print(ar[x]) 

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]))
[22 33 44 20 30 40 20 30 40 20 30 40]
