In [1]:
import numpy as np

In [2]:
ar=np.array([10,20,30,40])
print(ar)

[10 20 30 40]


In [3]:
print(ar+2)

[12 22 32 42]


In [4]:
print(ar-2)

[ 8 18 28 38]


In [5]:
print(ar*2)

[20 40 60 80]


In [6]:
print(ar**2)

[ 100  400  900 1600]


In [8]:
x=10
print(x)
x+=20
print(x)

10
30


In [9]:
#Modification in existing array
ar+=10
print(ar)

[20 30 40 50]


In [10]:
print(ar-1)

[19 29 39 49]
