Airthametic Operation in 2D array

In [2]:
import numpy as np

In [3]:
ar=np.array([[11,22,33],
             [10,20,30]])
print(ar)

[[11 22 33]
 [10 20 30]]


In [4]:
print(ar+2)

[[13 24 35]
 [12 22 32]]


In [5]:
print(ar[0])

[11 22 33]


In [6]:
print(ar[0]+10)

[21 32 43]


In [8]:
print(ar)
print('----------------')
ar[0]+=10
print(ar)

[[21 32 43]
 [10 20 30]]
----------------
[[31 42 53]
 [10 20 30]]


#### min , Max ,Sum Opertaion in array

In [9]:
ar=np.array([10,20,40,20])
print(ar)

[10 20 40 20]


In [12]:
print('Minimum value --> ',np.min(ar))
print('Maximum Value --> ',np.max(ar))
print('Sum of all elements --> ',np.sum(ar))

Minimum value -->  10
Maximum Value -->  40
Sum of all elements -->  90


In [16]:
#### In 2D -> Array

ar=np.array([[11,22,33],
             [10,20,30]])
print(ar)

[[11 22 33]
 [10 20 30]]


In [22]:
print(np.min(ar))
print(np.min(ar[0]))
print(np.min(ar,axis=0))


10
11
[10 20 30]


In [21]:
print ("Column-wise minimum elements:",ar.min(axis = 0))

Column-wise minimum elements: [10 20 30]


In [23]:
print ("Row-wise minimum elements:",ar.min(axis = 1))

Row-wise minimum elements: [11 10]


In [26]:
print("Max value --> ",ar.max())
print("Max values Column-wise -->: ",ar.max(axis=0))
print("Max values Row-wise -->: ",ar.max(axis=1))

Max value -->  33
Max values Column-wise -->:  [11 22 33]
Max values Row-wise -->:  [33 30]


In [29]:
print("Sum --> ",ar.sum())
print("Sum row1--> ",ar[0].sum())
print("Sum row1--> ",ar[1].sum())

Sum -->  126
Sum row1-->  66
Sum row1-->  60


In [32]:
# axis 0 --> col
# axis 1 -->row
# cumulative sum along each row
print(ar)
print('-------------')
print ("Cumulative sum along each row:\n", ar.cumsum(axis = 1))

#0 --> 11  22  33
 11  11+22   11+22+33

#1 --> 10 20 30
 10   10+20   10+20+30

[[11 22 33]
 [10 20 30]]
-------------
Cumulative sum along each row:
 [[11 33 66]
 [10 30 60]]


In [34]:
print(ar)
print('-------------------')
print ("Cumulative sum along each col:\n", ar.cumsum(axis = 0))
# col1  11 10
   11  11+10
#col2   22 20
    22   22+20

#col3  33 30
    33   33+30

[[11 22 33]
 [10 20 30]]
-------------------
Cumulative sum along each col:
 [[11 22 33]
 [21 42 63]]


In [ ]:
ar= [[10,11],
     [20,22],
     [30,33],
     [40,44]]

# 1. find shape 
# 2. find dimension
# 3. find type of element
# 4. find size of array
# 5. find minimum element
# 6. find max element
# 7. find minimum element along row and col
# 8. find minimum element in row 3rd
# 9. find max element along row and col
# 8. find max element in col 2nd
# 9. find sum of all element
# 10. find cumilative sum of  of all 

