In [1]:
import numpy as np

In [8]:
ar=np.array([[11,10],
             [22,20],
             [33,30]])
print(ar)
print('----------------')
print(ar.shape)

[[11 10]
 [22 20]
 [33 30]]
----------------
(3, 2)


In [3]:
print(ar.T)

[[11 22 33]
 [10 20 30]]


In [4]:
print(ar)

[[11 10]
 [22 20]
 [33 30]]


In [10]:
ar=ar.T     #modify in existing array
print(ar)
print(ar.shape)

[[11 22 33]
 [10 20 30]]
(2, 3)
