In [1]:
import numpy as np

In [2]:
#1d - Array
a1=np.array([10,20])
a2=np.array([11,22])
print(a1)
print(a2)

[10 20]
[11 22]


In [3]:
print(a1+a2)

[21 42]


In [4]:
print(a1*a2)

[110 440]


In [5]:
#2d -->Array
a1=np.array([[1,2],
             [3,4]])
a2=np.array([[10,20],
             [11,22]])

print(a1)
print(a2)

[[1 2]
 [3 4]]
[[10 20]
 [11 22]]


In [6]:
print(a1+a2)

[[11 22]
 [14 26]]


In [7]:
#Normal multipication
print(a1*a2)

[[10 40]
 [33 88]]


In [9]:
#matrix multipication
print(a1.dot(a2))

[[ 32  64]
 [ 74 148]]


In [ ]:
a1 ==> 1 2
a2 ==> 10 11

1*10 + 2*11

10+22 =32
#---------------------

a1 ==> 1 2
a2 ==> 20 22

1*20 + 2*22 = 62

In [10]:
#pi value
print(np.pi)

3.141592653589793


In [16]:
pi=np.pi
ar=np.array([0,pi/2,pi/3,pi/4]) 
print(ar)

[0.         1.57079633 1.04719755 0.78539816]


In [17]:
print(np.sin(ar))
print(np.cos(ar))
print(np.tan(ar))

[0.         1.         0.8660254  0.70710678]
[1.00000000e+00 6.12323400e-17 5.00000000e-01 7.07106781e-01]
[0.00000000e+00 1.63312394e+16 1.73205081e+00 1.00000000e+00]


In [18]:
#exponatial value
ar=np.array([1,2,3,4,5])
print(np.exp(ar))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [19]:
#Squer root
print(np.sqrt(ar))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [28]:
a1=np.array([10,20,30])
a2=np.array([1,2,3])
print(np.add(a1,a2))
print(np.subtract(a1,a2))
print(np.multiply(a1,a2))
print(np.divide(a2,a1))

[11 22 33]
[ 9 18 27]
[10 40 90]
[0.1 0.1 0.1]
