In [1]:
import numpy as np

In [3]:
ar=np.array([10,20,30,40])
print(ar)
print(ar.dtype)

[10 20 30 40]
int64


In [5]:
ar=np.array([10,20,30,40],dtype='float')
print(ar)
print(ar.dtype)

[10. 20. 30. 40.]
float64


In [6]:
ar=np.array([10,20,30,40])
print(ar)
print(ar.dtype)

[10 20 30 40]
int64


In [9]:
datatype1=np.dtype(np.int16)
print(datatype1)



int16


In [10]:
ar=np.array([10,20,30,40],dtype=datatype1)
print(ar.dtype)

int16


In [14]:
dt = np.dtype('>i4')
print("Byte order is:",dt.byteorder)
print("Size is:",dt.itemsize,' Bytes')
print("Data type is:",dt.name)


Byte order is: >
Size is: 4  Bytes
Data type is: int32


In [26]:

# the use of data type object with structured array.

dt = np.dtype([('name', np.str_,16), ('marks', np.float64,2)])

# x is a structured array with names and marks of students.
# Data type of name of the student is np.unicode_ and
# data type of marks is np.float64

data=[('Sara', (8.0, 7.0)), 
      ('John', (6.0, 7.0))]

x = np.array(data, dtype=dt)

print(x)
print(x[0])
print(x[1])

[('Sara', [8., 7.]) ('John', [6., 7.])]
('Sara', [8.0, 7.0])
('John', [6.0, 7.0])


In [20]:
print(x[1])
print("Marks of John are: ",x[1]['marks'])


('John', [6.0, 7.0])
Marks of John are:  [6. 7.]


In [21]:
print("Names are: ",x['name'])


Names are:  ['Sarah' 'John']


In [22]:
print("Makrs: ",x['marks'])

Makrs:  [[8. 7.]
 [6. 7.]]
